# Generated by Django 4.2.8 on 2024-01-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='birthdate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
