# Generated by Django 4.2.8 on 2024-01-06 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_petprofile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_profiles', to='myapp.profile'),
        ),
    ]
