# Generated by Django 4.2.8 on 2024-01-06 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_petprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
    ]
