# Generated by Django 4.2.8 on 2024-01-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_blogmodel_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='BlogPost',
        ),
    ]
