# Generated by Django 4.2.8 on 2024-01-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_nutritionitem_userreview_nutritionquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男の子'), ('female', '女の子')], max_length=10),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='neutered',
            field=models.CharField(choices=[('yes', '去勢・避妊済み'), ('no', '未去勢・未避妊')], max_length=3),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='vaccination',
            field=models.CharField(choices=[('yes', '接種済み'), ('no', '未接種')], max_length=3),
        ),
    ]
