# Generated by Django 4.2.8 on 2024-02-12 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionpost',
            old_name='health_info',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='adoptionpost',
            name='pet_age',
        ),
        migrations.RemoveField(
            model_name='adoptionpost',
            name='pet_gender',
        ),
        migrations.RemoveField(
            model_name='adoptionpost',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='adoptionpost',
            name='user',
        ),
        migrations.AddField(
            model_name='adoptionpost',
            name='address',
            field=models.CharField(default='未設定', max_length=255),
        ),
        migrations.AddField(
            model_name='adoptionpost',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptionpost',
            name='breed',
            field=models.CharField(default='不明', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptionpost',
            name='gender',
            field=models.CharField(default='不明', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptionpost',
            name='neutered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptionpost',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adoptionpost',
            name='pet_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adoptionpost',
            name='pet_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adoptionpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/'),
        ),
    ]
