# Generated by Django 4.2.8 on 2024-02-12 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_health_info_adoptionpost_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionpost',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
