# Generated by Django 4.2.8 on 2024-02-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_adoptionpost_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionpost',
            name='address',
        ),
        migrations.RemoveField(
            model_name='adoptionpost',
            name='pet_name',
        ),
        migrations.RemoveField(
            model_name='adoptionpost',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='adoptionpost',
            name='reason',
        ),
        migrations.AlterField(
            model_name='adoptionpost',
            name='breed',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
