# Generated by Django 4.2.8 on 2024-02-12 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_adoptionpost_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
