# Generated by Django 4.2.8 on 2024-02-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_adoptionpost_address_adoptionpost_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionpost',
            old_name='breed',
            new_name='pet_breed',
        ),
    ]
