# Generated by Django 4.2.8 on 2024-02-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_nutritionpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionpost',
            name='symptom',
        ),
        migrations.AlterField(
            model_name='nutritionpost',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nutritionpost',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
