# Generated by Django 4.2.8 on 2024-02-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_nutritionpost_symptom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionpost',
            name='symptom',
            field=models.CharField(blank=True, choices=[('skin', '皮膚'), ('digestion', '消化'), ('joints', '関節'), ('eyes_ears', '目と耳'), ('coat', '毛並み')], max_length=100),
        ),
    ]
