# Generated by Django 4.2.8 on 2024-02-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_nutritionpost_symptom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionpost',
            name='symptom',
            field=models.CharField(blank=True, choices=[('皮膚', '皮膚'), ('消化', '消化'), ('関節', '関節'), ('目と耳', '目と耳'), ('毛並み', '毛並み')], max_length=100),
        ),
    ]
