# Generated by Django 4.2.8 on 2024-02-18 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_petprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
