# Generated by Django 4.2.8 on 2024-02-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionpost',
            name='contact_info',
            field=models.TextField(default='', verbose_name='問い合わせ先'),
            preserve_default=False,
        ),
    ]
